request_list = [f"cuantos son dos mas dos.", f"4 + 9", f"What is a giraffe? reply with 5 words."]
request_list_dos = [
    f"cuantos son cuatro mas fem in danish.",
    f"7 + vier",
    f"What is an elephant? reply with 5 words.",
]

list_of_list_of_requests = [
    request_list,
    request_list_dos,
    request_list,
    request_list_dos,
    request_list,
    request_list_dos,
    request_list,
    request_list_dos,
    request_list,
    request_list_dos,
    request_list,
    request_list_dos,
    request_list,
    request_list_dos,
    request_list,
    request_list_dos,
    request_list,
    request_list_dos,
    request_list,
    request_list_dos,
    request_list,
    request_list_dos,
    request_list,
    request_list_dos,
    request_list,
    request_list_dos,
    request_list,
    request_list_dos,
    request_list,
    request_list_dos,
    request_list,
    request_list_dos,
]

list_of_requests_tandem = [
    f"cuantos son dos mas dos.",
    f"4 + 9",
    f"What is a giraffe? reply with 5 words.",
    f"cuantos son cuatro mas fem in danish.",
    f"7 + vier",
    f"What is an elephant? reply with 5 words.",
    f"cuantos son dos mas dos.",
    f"4 + 9",
    f"What is a giraffe? reply with 5 words.",
    f"cuantos son cuatro mas fem in danish.",
    f"7 + vier",
    f"What is an elephant? reply with 5 words.",
    f"cuantos son dos mas dos.",
    f"4 + 9",
    f"What is a giraffe? reply with 5 words.",
    f"cuantos son cuatro mas fem in danish.",
    f"7 + vier",
    f"What is an elephant? reply with 5 words.",
    f"cuantos son dos mas dos.",
    f"4 + 9",
    f"What is a giraffe? reply with 5 words.",
    f"cuantos son cuatro mas fem in danish.",
    f"7 + vier",
    f"What is an elephant? reply with 5 words.",
    f"cuantos son dos mas dos.",
    f"4 + 9",
    f"What is a giraffe? reply with 5 words.",
    f"cuantos son cuatro mas fem in danish.",
    f"7 + vier",
    f"What is an elephant? reply with 5 words.",
    f"cuantos son dos mas dos.",
    f"4 + 9",
    f"What is a giraffe? reply with 5 words.",
    f"cuantos son cuatro mas fem in danish.",
    f"7 + vier",
    f"What is an elephant? reply with 5 words.",
    f"cuantos son dos mas dos.",
    f"4 + 9",
    f"What is a giraffe? reply with 5 words.",
    f"cuantos son cuatro mas fem in danish.",
    f"7 + vier",
    f"What is an elephant? reply with 5 words.",
    f"cuantos son dos mas dos.",
    f"4 + 9",
    f"What is a giraffe? reply with 5 words.",
    f"cuantos son cuatro mas fem in danish.",
    f"7 + vier",
    f"What is an elephant? reply with 5 words.",
    f"cuantos son dos mas dos.",
    f"4 + 9",
    f"What is a giraffe? reply with 5 words.",
    f"cuantos son cuatro mas fem in danish.",
    f"7 + vier",
    f"What is an elephant? reply with 5 words.",
    f"cuantos son dos mas dos.",
    f"4 + 9",
    f"What is a giraffe? reply with 5 words.",
    f"cuantos son cuatro mas fem in danish.",
    f"7 + vier",
    f"What is an elephant? reply with 5 words.",
    f"cuantos son dos mas dos.",
    f"4 + 9",
    f"What is a giraffe? reply with 5 words.",
    f"cuantos son cuatro mas fem in danish.",
    f"7 + vier",
    f"What is an elephant? reply with 5 words.",
    f"cuantos son dos mas dos.",
    f"4 + 9",
    f"What is a giraffe? reply with 5 words.",
    f"cuantos son cuatro mas fem in danish.",
    f"7 + vier",
    f"What is an elephant? reply with 5 words.",
    f"cuantos son dos mas dos.",
    f"4 + 9",
    f"What is a giraffe? reply with 5 words.",
    f"cuantos son cuatro mas fem in danish.",
    f"7 + vier",
    f"What is an elephant? reply with 5 words.",
    f"cuantos son dos mas dos.",
    f"4 + 9",
    f"What is a giraffe? reply with 5 words.",
    f"cuantos son cuatro mas fem in danish.",
    f"7 + vier",
    f"What is an elephant? reply with 5 words.",
    f"cuantos son dos mas dos.",
    f"4 + 9",
    f"What is a giraffe? reply with 5 words.",
    f"cuantos son cuatro mas fem in danish.",
    f"7 + vier",
    f"What is an elephant? reply with 5 words.",
    f"cuantos son dos mas dos.",
    f"4 + 9",
    f"What is a giraffe? reply with 5 words.",
    f"cuantos son cuatro mas fem in danish.",
    f"7 + vier",
    f"What is an elephant? reply with 5 words.",
]
